# Generated by Django 6.0.4 on 2026-04-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPANY_EMAIL', 'company_email'), ('PAYMENT_REQUEST', 'payment_request'), ('JOB_OFFER', 'job_offer'), ('ID_DEP', 'it_dep'), ('SCAM_IPHONE', 'scam_iphone'), ('SCAM_LOTTERY', 'scam_lottery'), ('SECURITY_ALERT', 'security_alert')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('CLICK', 'click'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('recive_date', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='PhishingShark.employes')),
            ],
        ),
    ]
