# Generated by Django 6.0.4 on 2026-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0002_emailtracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtracking',
            old_name='recive_date',
            new_name='clicked_at',
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
