# Generated by Django 6.0.4 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0003_rename_recive_date_emailtracking_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
