# Generated by Django 6.0.4 on 2026-04-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0005_alter_administrateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='is_supperuser',
        ),
    ]
