# Generated by Django 6.0.4 on 2026-04-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0006_remove_administrateur_is_supperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('email_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_credentials', to='PhishingShark.emailtracking')),
            ],
        ),
    ]
