# Generated by Django 6.0.4 on 2026-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0007_capturedcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('CLICK', 'click'), ('CREDENTIALS_CAPTURED', 'Credentials Captured'), ('TRAINING_COMPLETED', 'Training Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
