# Generated by Django 6.0.4 on 2026-04-29 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0008_alter_emailtracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
