# Generated by Django 6.0.4 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0009_alter_emailtracking_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
