# Generated by Django 6.0.4 on 2026-05-19 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0010_departement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
