# Generated by Django 6.0.4 on 2026-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QcmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_matricule', models.CharField(max_length=100, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('start_at', models.TimeField()),
                ('finish_at', models.TimeField()),
                ('totale_qcm_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensibilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_matricule', models.CharField(max_length=100)),
                ('totale_time', models.TimeField()),
            ],
        ),
    ]
