# Generated by Django 6.0.4 on 2026-05-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0010_departement_is_active'),
        ('Sensibilisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensibilisation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='PhishingShark.employes'),
        ),
        migrations.AddField(
            model_name='sensibilisation',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AlertsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('CLICK', 'click'), ('CREDENTIALS_CAPTURED', 'Credentials Captured'), ('TRAINING_COMPLETED', 'Training Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_email', to='PhishingShark.employes')),
            ],
        ),
    ]
