# Generated by Django 6.0.4 on 2026-05-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhishingShark', '0010_departement_is_active'),
        ('Sensibilisation', '0002_sensibilisation_employee_sensibilisation_read_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensibilisation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensibilisation', to='PhishingShark.employes'),
        ),
    ]
