# Generated by Django 6.0.4 on 2026-05-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensibilisation', '0003_alter_sensibilisation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcmresult',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
